apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: employee-app
  name: employee-app
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: emplloyee-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: "2022-05-16T12:54:57Z"
      labels:
        app: employee-app
    spec:
      containers:
      - image: prasadijaya/employee-docker-image:{{tag}}
        imagePullPolicy: Always
        name: employee-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
